# 케라스로 만드는 회귀 예제

매사추세츠 보스턴 지역의 주택 가격 예측하기

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/rickiepark/dl-illustrated/blob/master/notebooks/9-3.regression_in_keras.ipynb)

#### 라이브러리를 적재합니다.

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout 
from tensorflow.keras.layers import BatchNormalization 

#### 데이터를 적재합니다.

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

57344/57026 [==============================] - 0s 0us/step


In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

#### 신경망을 만듭니다.

In [7]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                448       
_________________________________________________________________
batch_normalization (BatchNo (None, 32)                128       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_1 (Batch (None, 16)                64        
_________________________________________________________________
dropout (Dropout)            (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
Total params: 1,185
Trainable params: 1,089
Non-trainable params: 96
_____________________________________________________

#### 모델을 설정합니다.

In [9]:
model.compile(loss='mean_squared_error', optimizer='adam')

#### 훈련!

In [10]:
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid))

Epoch 1/32
51/51 [==============================] - 3s 9ms/step - loss: 558.3180 - val_loss: 699.8416
Epoch 2/32
51/51 [==============================] - 0s 3ms/step - loss: 612.4030 - val_loss: 645.0358
Epoch 3/32
51/51 [==============================] - 0s 3ms/step - loss: 566.0649 - val_loss: 602.0720
Epoch 4/32
51/51 [==============================] - 0s 3ms/step - loss: 518.8130 - val_loss: 569.3940
Epoch 5/32
51/51 [==============================] - 0s 4ms/step - loss: 536.8539 - val_loss: 542.1461
Epoch 6/32
51/51 [==============================] - 0s 3ms/step - loss: 456.3808 - val_loss: 461.2923
Epoch 7/32
51/51 [==============================] - 0s 4ms/step - loss: 417.9323 - val_loss: 401.2823
Epoch 8/32
51/51 [==============================] - 0s 4ms/step - loss: 386.9893 - val_loss: 322.3392
Epoch 9/32
51/51 [==============================] - 0s 4ms/step - loss: 416.3226 - val_loss: 271.6992
Epoch 10/32
51/51 [==============================] - 0s 4ms/step - loss: 319.9924 

In [11]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [12]:
y_valid[42]

14.1

In [13]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[22.953802]], dtype=float32)